# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('disc_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code')),
                ('disc_desc', models.CharField(max_length=60, verbose_name='description')),
                ('disc_percent', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='percentage')),
            ],
            options={
                'verbose_name_plural': 'Discounts',
                'verbose_name': 'discount',
                'db_table': 'oh_discount',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('prod_name', models.CharField(max_length=60, verbose_name='name')),
                ('prod_desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'product',
                'db_table': 'oh_product',
            },
        ),
        migrations.CreateModel(
            name='ProductBasis',
            fields=[
                ('prdb_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('prdb_is_active', models.CharField(default='Y', max_length=1, verbose_name='active')),
                ('prdb_list_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='basis')),
                ('prod_code', models.ForeignKey(db_column='prod_code', on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'Productsbasis',
                'verbose_name': 'productbasis',
                'db_table': 'oh_product_basis',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('pdis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('pdis_name', models.CharField(max_length=60, verbose_name='description')),
                ('pdis_start_date', models.DateField(blank=True, null=True, verbose_name='startdate')),
                ('pdis_end_date', models.DateField(blank=True, null=True, verbose_name='enddate')),
                ('disc_code', models.ForeignKey(db_column='disc_code', on_delete=django.db.models.deletion.DO_NOTHING, to='products.Discount', verbose_name='discount')),
                ('prdb_id', models.ForeignKey(db_column='prdb_id', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductBasis', verbose_name='productbasis')),
            ],
            options={
                'verbose_name_plural': 'ProductDiscounts',
                'verbose_name': 'productdiscount',
                'db_table': 'oh_product_discount',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('prdt_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='producttype')),
                ('prdt_desc', models.CharField(max_length=60, verbose_name='description')),
                ('prdt_is_fulfill_manual', models.CharField(max_length=1, verbose_name='fulfillmentmanual')),
            ],
            options={
                'verbose_name_plural': 'ProductTypes',
                'verbose_name': 'producttype',
                'db_table': 'oh_product_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_code',
            field=models.ForeignKey(db_column='prdt_code', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductType', verbose_name='producttype'),
        ),
    ]
