# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='company')),
                ('comp_id_parent', models.IntegerField(blank=True, null=True, verbose_name='parentcompany')),
                ('name', models.CharField(db_column='comp_name', max_length=30, verbose_name='name')),
                ('email', models.CharField(blank=True, db_column='comp_email', max_length=40, null=True, verbose_name='email')),
                ('website', models.CharField(blank=True, db_column='comp_website', max_length=60, null=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, db_column='comp_phone', max_length=20, null=True, verbose_name='phone')),
                ('fax', models.CharField(blank=True, db_column='comp_fax', max_length=20, null=True, verbose_name='fax')),
                ('address', models.ForeignKey(blank=True, db_column='addr_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Address', verbose_name='address')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'verbose_name': 'company',
                'db_table': 'oh_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clng_is_preferred', models.CharField(blank=True, max_length=1, null=True, verbose_name='preferredlanguage')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Company', verbose_name='company')),
                ('lang_code', models.ForeignKey(db_column='lang_code', default='ENG', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Language', verbose_name='languagecode')),
            ],
            options={
                'verbose_name': 'companylanguage',
                'verbose_name_plural': 'companylanguages',
                'db_table': 'oh_company_language',
            },
        ),
        migrations.CreateModel(
            name='CompanyPersonRole',
            fields=[
                ('cprs_id', models.AutoField(primary_key=True, serialize=False)),
                ('cprs_start_date', models.DateField(blank=True, null=True, verbose_name='startdate')),
                ('cprs_end_date', models.DateField(blank=True, null=True, verbose_name='enddate')),
                ('comp', models.ForeignKey(db_column='comp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Company', verbose_name='company')),
                ('cprs_id_manager', models.ForeignKey(blank=True, db_column='cprs_id_manager', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.CompanyPersonRole', verbose_name='manager')),
            ],
            options={
                'verbose_name_plural': 'companypersonroles',
                'verbose_name': 'companypersonrole',
                'db_table': 'oh_company_person_role',
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('crol_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('crol_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'companyroles',
                'verbose_name': 'companyrole',
                'db_table': 'oh_company_role',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('prsn_id', models.AutoField(primary_key=True, serialize=False, verbose_name='person')),
                ('first_name', models.CharField(db_column='prsn_fname', max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(db_column='prsn_lname', max_length=20, verbose_name='last name')),
                ('office_phone', models.CharField(blank=True, db_column='prsn_office_phone', max_length=20, null=True, verbose_name='office phone')),
                ('mobile_phone', models.CharField(blank=True, db_column='prsn_mobile_phone', max_length=20, null=True, verbose_name='mobile phone')),
                ('fax', models.CharField(blank=True, db_column='prsn_fax', max_length=20, null=True, verbose_name='fax')),
                ('email', models.CharField(blank=True, db_column='prsn_email', max_length=60, null=True, verbose_name='email')),
                ('skype', models.CharField(blank=True, db_column='prsn_skype', max_length=40, null=True, verbose_name='skype')),
                ('facebook', models.CharField(blank=True, db_column='prsn_facebook', max_length=40, null=True, verbose_name='facebook')),
                ('notes', models.TextField(blank=True, db_column='prsn_notes', null=True, verbose_name='notes')),
                ('address', models.ForeignKey(blank=True, db_column='addr_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Address', verbose_name='address')),
            ],
            options={
                'verbose_name_plural': 'Person',
                'verbose_name': 'person',
                'db_table': 'oh_person',
            },
        ),
        migrations.CreateModel(
            name='PersonLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plng_is_preferred', models.CharField(blank=True, max_length=1, null=True, verbose_name='preferredlanguage')),
                ('lang_code', models.ForeignKey(db_column='lang_code', default='ENG', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Language', verbose_name='languagecode')),
                ('prsn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'personlanguage',
                'verbose_name_plural': 'personlanguages',
                'db_table': 'oh_person_language',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('subs_naic_group_level', models.IntegerField(verbose_name='default')),
                ('subs_cc_exp_date', models.DateField(verbose_name='ccexpiredate')),
                ('subs_api_id', models.IntegerField(blank=True, default='000001', null=True, verbose_name='subscriptionapi')),
                ('subs_alert_date', models.DateField(blank=True, null=True, verbose_name='alertdate')),
                ('subs_referring_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='referring_url')),
                ('subs_api_payment_id', models.IntegerField(default='000001')),
                ('subs_payment_method', models.CharField(default='C', max_length=1)),
                ('subs_termination_date', models.DateTimeField(blank=True, null=True, verbose_name='terminationdate')),
                ('subs_termination_reason', models.CharField(blank=True, max_length=2000, null=True, verbose_name='reason')),
                ('comp', models.ForeignKey(db_column='comp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Company', verbose_name='company')),
                ('naic_level_5_code', models.ForeignKey(db_column='naic_level_5_code', default='722511', on_delete=django.db.models.deletion.DO_NOTHING, to='management.NaicsLevel5', verbose_name='naicslevel5')),
                ('ssrc', models.ForeignKey(db_column='ssrc_id', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Salessource', verbose_name='salessource')),
            ],
            options={
                'verbose_name_plural': 'subscriptions',
                'verbose_name': 'subscription',
                'db_table': 'oh_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('subd_id', models.AutoField(primary_key=True, serialize=False)),
                ('subd_start_date', models.DateField(verbose_name='subscriptionstartdate')),
                ('subd_end_date', models.DateField(verbose_name='subscriptionenddate')),
                ('subd_list_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='listprice')),
                ('subd_discount_percent', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='discount')),
                ('subd_net_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='netprice')),
                ('subd_sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='salestax')),
                ('subd_date', models.DateTimeField(verbose_name='subscribeddate')),
                ('cprs', models.ForeignKey(blank=True, db_column='cprs_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.CompanyPersonRole', verbose_name='companypersonrole')),
                ('pdis', models.ForeignKey(blank=True, db_column='pdis_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductDiscount', verbose_name='productdiscount')),
                ('prdb', models.ForeignKey(db_column='prdb_id', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductBasis', verbose_name='productbasis')),
                ('subd_id_first', models.ForeignKey(db_column='subd_id_first', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.SubscriptionDetail')),
                ('subs', models.ForeignKey(db_column='subs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name_plural': 'subscriptionsdetails',
                'verbose_name': 'subscriptiondetail',
                'db_table': 'oh_subscription_detail',
            },
        ),
        migrations.AddField(
            model_name='companypersonrole',
            name='crol_code',
            field=models.ForeignKey(db_column='crol_code', default='OWNER', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.CompanyRole', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='companypersonrole',
            name='prsn',
            field=models.ForeignKey(db_column='prsn_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Person', verbose_name='person'),
        ),
        migrations.AlterUniqueTogether(
            name='personlanguage',
            unique_together=set([('prsn', 'lang_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='companylanguage',
            unique_together=set([('comp', 'lang_code')]),
        ),
    ]
