# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('subu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perm_code', models.ForeignKey(db_column='perm_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Permission')),
                ('subs', models.ForeignKey(db_column='subs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Subscription', verbose_name='Subscription')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'SubscriptionUsers',
                'verbose_name': 'SubscriptionUser',
                'db_table': 'oh_subscription_user',
            },
        ),
    ]
