# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20170104_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, db_column='prsn_lname', max_length=20, null=True, verbose_name='last name'),
        ),
    ]
