# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohfunction',
            name='func_id',
            field=models.CharField(db_column='func_id', max_length=60, primary_key=True, serialize=False, verbose_name='function'),
        ),
    ]
