# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('subm_id', models.AutoField(primary_key=True, serialize=False)),
                ('subm_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='amount')),
                ('subm_ref', models.CharField(blank=True, max_length=60, null=True, verbose_name='reference')),
                ('subm_desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='description')),
                ('subm_alert_date', models.DateField(blank=True, null=True, verbose_name='alertdate')),
                ('subm_due_date', models.DateField(verbose_name='duedate')),
                ('subm_file_date', models.DateField(blank=True, null=True, verbose_name='filedate')),
                ('subm_preparer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='preparerfee')),
                ('subm_date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='basis')),
                ('cprs', models.ForeignKey(db_column='cprs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.CompanyPersonRole', verbose_name='subscription')),
            ],
            options={
                'verbose_name_plural': 'submission',
                'verbose_name': 'submission',
                'db_table': 'oh_submission',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('suba_id', models.AutoField(primary_key=True, serialize=False)),
                ('suba_date', models.DateTimeField(verbose_name='date')),
                ('suba_note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('suba_attachment', models.TextField(verbose_name='attachment')),
                ('atyp_code', models.ForeignKey(db_column='atyp_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.AttachmentType', verbose_name='attachmenttype')),
                ('subm', models.ForeignKey(db_column='subs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='submission.Submission', verbose_name='submission')),
            ],
            options={
                'verbose_name_plural': 'submissionattachments',
                'verbose_name': 'submissionattachment',
                'db_table': 'oh_submission_attachment',
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('subt_id', models.AutoField(primary_key=True, serialize=False)),
                ('subt_desc', models.CharField(max_length=60)),
                ('agen_code', models.ForeignKey(db_column='agen_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Agency', verbose_name='agency')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='basis')),
            ],
            options={
                'verbose_name_plural': 'subscriptions',
                'verbose_name': 'submissiontype',
                'db_table': 'oh_submission_type',
            },
        ),
        migrations.CreateModel(
            name='SubmissionTypeJurisdiction',
            fields=[
                ('subj_id', models.AutoField(primary_key=True, serialize=False)),
                ('subj_help_text', models.TextField(blank=True, null=True, verbose_name='agency')),
                ('jurs', models.ForeignKey(db_column='agen_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Jurisdiction', verbose_name='jurisdiction')),
                ('subt', models.ForeignKey(db_column='subt_id', on_delete=django.db.models.deletion.DO_NOTHING, to='submission.SubmissionType', verbose_name='submissiontype')),
            ],
            options={
                'verbose_name_plural': 'submissiontypejurisdiction',
                'verbose_name': 'submissiontypejurisdiction',
                'db_table': 'oh_submission_type_jurisdiction',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='subj',
            field=models.ForeignKey(db_column='subj_id', on_delete=django.db.models.deletion.DO_NOTHING, to='submission.SubmissionTypeJurisdiction', verbose_name='submissiontypejurisdiction'),
        ),
        migrations.AddField(
            model_name='submission',
            name='subs',
            field=models.ForeignKey(db_column='subs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Subscription', verbose_name='subscription'),
        ),
    ]
