# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system_alert', 'System Generated Alert'), ('user_alert', 'User Generated Alert'), ('customer_alert', 'Customer Generated Alert')], max_length=255)),
                ('data', models.TextField(default='{}')),
                ('dt_event', models.DateTimeField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.SubscriptionDetail')),
            ],
            options={
                'ordering': ('-dt_event', 'customer'),
            },
        ),
    ]
