# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCarrier',
            fields=[
                ('icar_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp', models.ForeignKey(db_column='comp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Company', verbose_name='company')),
            ],
            options={
                'verbose_name_plural': 'insurancecarrier',
                'verbose_name': 'insurancecarrier',
                'db_table': 'oh_insurance_carrier',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocType',
            fields=[
                ('idoc_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('idoc_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'insurancedoctype',
                'verbose_name': 'insurancedoctype',
                'db_table': 'oh_insurance_doc_type',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('ipol_id', models.AutoField(primary_key=True, serialize=False)),
                ('ipol_alert_date', models.DateField(blank=True, null=True, verbose_name='alertdate')),
                ('ipol_start_date', models.DateField(blank=True, null=True, verbose_name='startdate')),
                ('ipol_end_date', models.DateField(blank=True, null=True, verbose_name='enddate')),
                ('ipol_policy_no', models.CharField(blank=True, max_length=40, null=True, verbose_name='policy_no')),
                ('ipol_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='premium')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='jurisdiction')),
                ('cprs', models.ForeignKey(blank=True, db_column='cprs_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.CompanyPersonRole', verbose_name='companypersonrole')),
                ('fina', models.ForeignKey(blank=True, db_column='fina_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Financing', verbose_name='financing')),
                ('icar', models.ForeignKey(blank=True, db_column='icar_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsuranceCarrier', verbose_name='insurancecarrier')),
            ],
            options={
                'verbose_name_plural': 'insurancepolicies',
                'verbose_name': 'insurancepolicy',
                'db_table': 'oh_insurance_policy',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicyAtt',
            fields=[
                ('ipat_id', models.AutoField(primary_key=True, serialize=False)),
                ('ipat_title', models.CharField(max_length=60, verbose_name='title')),
                ('ipat_note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('ipat_attachment', models.TextField(verbose_name='attachment')),
                ('ipat_date', models.DateTimeField(verbose_name='date')),
                ('ipat_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='filename')),
                ('atyp_code', models.ForeignKey(db_column='atyp_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.AttachmentType', verbose_name='attachmenttype')),
                ('idoc_code', models.ForeignKey(db_column='idoc_code', on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsuranceDocType', verbose_name='insurancedoctype')),
                ('ipol', models.ForeignKey(db_column='insj_id', on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsurancePolicy', verbose_name='insurancepolicy')),
            ],
            options={
                'verbose_name_plural': 'insurancepolicyatt',
                'verbose_name': 'insurancepolicyatt',
                'db_table': 'oh_insurance_policy_att',
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('inty_id', models.AutoField(primary_key=True, serialize=False)),
                ('inty_desc', models.CharField(max_length=60, verbose_name='description')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='basis')),
                ('agen_code', models.ForeignKey(db_column='agen_code', on_delete=django.db.models.deletion.DO_NOTHING,
                                                to='management.Agency', verbose_name='agency')),

            ],
            options={
                'verbose_name_plural': 'insurancetypes',
                'verbose_name': 'insurancetype',
                'db_table': 'oh_insurance_type',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTypeJurisdiction',
            fields=[
                ('insj_id', models.AutoField(primary_key=True, serialize=False)),
                ('insj_help_text', models.TextField(blank=True, null=True, verbose_name='helptext')),
                ('inty', models.ForeignKey(db_column='inty_id', on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsuranceType', verbose_name='insurancetype')),
                ('cont', models.ForeignKey(db_column='cont_id', on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='management.County', verbose_name='county')),
                ('govl_code', models.ForeignKey(db_column='govl_code', on_delete=django.db.models.deletion.DO_NOTHING,
                                                to='management.GovernmentLevel', verbose_name='govermentlevel')),
            ],
            options={
                'verbose_name': 'insurancetypejurisdiction',
                'verbose_name_plural': 'insurancetypejurisdictions',
                'db_table': 'oh_insurance_type_jurisdiction',
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insj',
            field=models.ForeignKey(db_column='insj_id', on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsuranceTypeJurisdiction', verbose_name='insurancetypejurisdiction'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='subs',
            field=models.ForeignKey(db_column='subs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='subscription.Subscription', verbose_name='subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='insurancetypejurisdiction',
            unique_together=set([('inty', 'cont', 'govl_code')]),
        ),
    ]
