# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='insurancetypejurisdiction',
        #     name='cont',
        #     field=models.ForeignKey(db_column='cont_id', default='1859', on_delete=django.db.models.deletion.DO_NOTHING, to='management.County', verbose_name='county'),
        # ),
        # migrations.AddField(
        #     model_name='insurancetypejurisdiction',
        #     name='govl_code',
        #     field=models.ForeignKey(db_column='govl_code', default='M', on_delete=django.db.models.deletion.DO_NOTHING, to='management.GovernmentLevel'),
        # ),
        # migrations.RemoveField(
        #     model_name='insurancetypejurisdiction',
        #     name='jurs',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='insurancetypejurisdiction',
        #     unique_together=set([('inty', 'cont', 'govl_code')]),
        # ),
    ]
