# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('insurance', '0002_auto_20161208_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetypejurisdiction',
            name='cont',
            field=models.ForeignKey(db_column='cont_id', default='1859', on_delete=django.db.models.deletion.DO_NOTHING, to='management.County', verbose_name='county'),
        ),
        migrations.AlterField(
            model_name='insurancetypejurisdiction',
            name='govl_code',
            field=models.ForeignKey(db_column='govl_code', default='M', on_delete=django.db.models.deletion.DO_NOTHING, to='management.GovernmentLevel'),
        ),
        migrations.AlterUniqueTogether(
            name='insurancetypejurisdiction',
            unique_together=set([('inty', 'cont', 'govl_code')]),
        ),
    ]
