# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_userpreferencetype_v_dashboard_service'),
        ('users', '0003_auto_20161224_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('uprf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uprf_value', models.CharField(max_length=40, verbose_name='UserPreferenceValue')),
                ('uprt_code', models.ForeignKey(db_column='uprt_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.UserPreferenceType', verbose_name='UserPreferenceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'UserPreferences',
                'db_table': 'oh_user_preference',
                'verbose_name': 'UserPreference',
            },
        ),
    ]
