# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='uprf_id',
            field=models.AutoField(db_column='uprf_id', primary_key=True, serialize=False, verbose_name='UserPreferencId'),
        ),
    ]
