# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('address_line_1', models.CharField(db_column='addr_line1', max_length=40, verbose_name='addressline1')),
                ('address_line_2', models.CharField(blank=True, db_column='addr_line2', max_length=40, null=True, verbose_name='addressline2')),
            ],
            options={
                'verbose_name_plural': 'address',
                'verbose_name': 'address',
                'db_table': 'oh_address',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agen_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('agen_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='name')),
                ('agen_website', models.CharField(blank=True, max_length=60, null=True, verbose_name='website')),
            ],
            options={
                'verbose_name_plural': 'agency',
                'verbose_name': 'agency',
                'db_table': 'oh_agency',
            },
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('atyp_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('atyp_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'attachmenttypes',
                'verbose_name': 'attachmenttype',
                'db_table': 'oh_attachment_type',
            },
        ),
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('basi_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('basi_alert_days', models.IntegerField(verbose_name='alertdays')),
                ('basi_repeat_alert_days', models.IntegerField(verbose_name='repeatalertdays')),
                ('basi_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'basis',
                'verbose_name': 'basis',
                'db_table': 'oh_basis',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_column='city_name', max_length=60, verbose_name='name')),
                ('city_is_user_added', models.CharField(default='n', max_length=1, verbose_name='city_user_added')),
            ],
            options={
                'verbose_name_plural': 'city',
                'verbose_name': 'city',
                'db_table': 'oh_city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_column='ctry_code', max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(db_column='ctry_name', max_length=60, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'verbose_name': 'country',
                'db_table': 'oh_country',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('cont_id', models.AutoField(db_column='cont_id', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_column='cont_name', max_length=60, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'counties',
                'verbose_name': 'county',
                'db_table': 'oh_county',
            },
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('fina_id', models.AutoField(primary_key=True, serialize=False)),
                ('fina_start_date', models.DateField(verbose_name='startdate')),
                ('fina_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='amount')),
                ('fina_downpay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='downpayment')),
                ('fina_period_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='paymentperiod')),
                ('fina_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='rate')),
                ('fina_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='fee')),
                ('fina_pay_start_date', models.DateField(blank=True, null=True, verbose_name='paymentstartdate')),
                ('fina_last_pay_date', models.DateField(blank=True, null=True, verbose_name='lastpaymentdate')),
                ('basi_code', models.ForeignKey(db_column='basi_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Basis', verbose_name='basis')),
            ],
            options={
                'verbose_name_plural': 'financing',
                'verbose_name': 'financing',
                'db_table': 'oh_financing',
            },
        ),
        migrations.CreateModel(
            name='GovernmentLevel',
            fields=[
                ('govl_code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='code')),
                ('govl_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'govermentlevel',
                'verbose_name': 'govermentlevel',
                'db_table': 'oh_government_level',
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('jurs_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.City', verbose_name='city')),
                ('govl_code', models.ForeignKey(db_column='govl_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.GovernmentLevel', verbose_name='govermentlevel')),
            ],
            options={
                'verbose_name_plural': 'jurisdiction',
                'verbose_name': 'jurisdiction',
                'db_table': 'oh_jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('lang_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'languages',
                'verbose_name': 'language',
                'db_table': 'oh_language',
            },
        ),
        migrations.CreateModel(
            name='NaicsLevel1',
            fields=[
                ('naic_level_1_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('naic_level_1_desc', models.CharField(max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'NaicsLevel1',
                'verbose_name': 'NaicsLevel1',
                'db_table': 'oh_naics_level_1',
            },
        ),
        migrations.CreateModel(
            name='NaicsLevel2',
            fields=[
                ('naic_level_2_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('naic_level_2_desc', models.CharField(max_length=60, verbose_name='description')),
                ('naic_level_1_code', models.ForeignKey(db_column='naic_level_1_code', default='72', on_delete=django.db.models.deletion.DO_NOTHING, to='management.NaicsLevel1', verbose_name='naicslevel1code')),
            ],
            options={
                'verbose_name_plural': 'NaicsLevel2',
                'verbose_name': 'naicslevel2',
                'db_table': 'oh_naics_level_2',
            },
        ),
        migrations.CreateModel(
            name='NaicsLevel3',
            fields=[
                ('naic_level_3_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='code')),
                ('naic_level_3_desc', models.CharField(max_length=60, verbose_name='description')),
                ('naic_level_2_code', models.ForeignKey(db_column='naic_level_2_code', default='722', on_delete=django.db.models.deletion.DO_NOTHING, to='management.NaicsLevel2', verbose_name='naicslevel2code')),
            ],
            options={
                'verbose_name_plural': 'NaicsLevel3',
                'verbose_name': 'naicslevel3',
                'db_table': 'oh_naics_level_3',
            },
        ),
        migrations.CreateModel(
            name='NaicsLevel4',
            fields=[
                ('naic_level_4_code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='code')),
                ('naic_level_4_desc', models.CharField(max_length=60, verbose_name='description')),
                ('naic_level_3_code', models.ForeignKey(db_column='naic_level_3_code', default='7225', on_delete=django.db.models.deletion.DO_NOTHING, to='management.NaicsLevel3', verbose_name='naicslevel3code')),
            ],
            options={
                'verbose_name_plural': 'NaicsLevel4',
                'verbose_name': 'naicslevel4',
                'db_table': 'oh_naics_level_4',
            },
        ),
        migrations.CreateModel(
            name='NaicsLevel5',
            fields=[
                ('naic_level_5_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('naic_level_5_desc', models.CharField(max_length=60, verbose_name='description')),
                ('naic_level_4_code', models.ForeignKey(db_column='naic_level_4_code', default='72251', on_delete=django.db.models.deletion.DO_NOTHING, to='management.NaicsLevel4', verbose_name='naicslevel4code')),
            ],
            options={
                'verbose_name_plural': 'NaicsLevel5',
                'verbose_name': 'naicslevel5',
                'db_table': 'oh_naics_level_5',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_code', models.CharField(db_column='role_code', max_length=6, primary_key=True, serialize=False, verbose_name='code')),
                ('role_desc', models.CharField(db_column='role_desc', max_length=60, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'roles',
                'verbose_name': 'role',
                'db_table': 'oh_role',
            },
        ),
        migrations.CreateModel(
            name='Salessource',
            fields=[
                ('ssrc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssrc_desc', models.CharField(max_length=60, verbose_name='description')),
                ('ssrc_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'salessources',
                'verbose_name': 'salessource',
                'db_table': 'oh_sales_source',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(db_column='stat_code', max_length=2, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(db_column='stat_name', max_length=60, verbose_name='name')),
                ('state_is_collect_sales_tax', models.CharField(default='N', max_length=1)),
                ('state_sales_tax_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('country', models.ForeignKey(db_column='ctry_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Country', verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'states',
                'verbose_name': 'state',
                'db_table': 'oh_state',
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipc_code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id')),
                ('county', models.ForeignKey(db_column='cont_id', on_delete=django.db.models.deletion.DO_NOTHING, to='management.County', verbose_name='county')),
            ],
            options={
                'verbose_name_plural': 'Zipcodes',
                'verbose_name': 'zipcode',
                'db_table': 'oh_zip',
            },
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(db_column='stat_code', on_delete=django.db.models.deletion.DO_NOTHING, to='management.State', verbose_name='state'),
        ),
        migrations.AddField(
            model_name='city',
            name='zipc_code',
            field=models.ForeignKey(db_column='zipc_code', default='16595', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Zipcode', verbose_name='zipcode'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.DO_NOTHING, to='management.City', verbose_name='city'),
        ),
    ]
