# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('compliance', '0004_auto_20161213_1934'),
        ('insurance', '0003_auto_20161213_1934'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='govl_code',
        ),
        migrations.DeleteModel(
            name='Jurisdiction',
        ),
    ]
