# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20161213_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_SubscribedServicesTable',
            fields=[
                ('csrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Service', models.CharField(default='Service', max_length=10, verbose_name='Service')),
                ('ctyp_desc', models.CharField(max_length=60, verbose_name='description')),
                ('csrv_due_date', models.DateField(verbose_name='duedate')),
                ('csac_date', models.DateTimeField(verbose_name='date')),
                ('csac_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='price')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='average_price')),
                ('off_from_avg', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, verbose_name='off_from_avg')),
                ('agen_code', models.CharField(max_length=6, primary_key=True, verbose_name='code')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'v_SubscribedServicesTable',
                'verbose_name': 'v_SubscribedServicesTable',
                'db_table': 'v_SubscribedServicesTable',
            },
        ),
    ]
