# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_v_subscribedservicestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_dashboard_service',
            fields=[
                ('csrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Service', models.CharField(default='Service', max_length=10, verbose_name='Service')),
                ('ctyp_desc', models.CharField(max_length=60, verbose_name='description')),
                ('csrv_due_date', models.DateField(verbose_name='duedate')),
                ('csac_service_date', models.DateField(verbose_name='servicedate')),
                ('csac_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='price')),
                ('average_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='average_price')),
                ('csac_price_last', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='off_from_avg')),
                ('csac_service_date_last', models.DateField(verbose_name='lastservicedate')),
                ('off_from_avg', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, verbose_name='off_from_avg')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'v_SubscribedServicesTable',
                'verbose_name': 'v_SubscribedServicesTable',
                'db_table': 'v_SubscribedServicesTable',
            },
        ),
    ]
