# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_s_dashboard_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s_dashboard_service',
            options={'managed': False, 'verbose_name': 's_dashboard_service', 'verbose_name_plural': 's_dashboard_service'},
        ),
        migrations.AlterModelTable(
            name='s_dashboard_service',
            table='s_dashboard_service',
        ),
    ]
