# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170103_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Code')),
                ('perm_desc', models.CharField(max_length=60, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'oh_permission',
            },
        ),
    ]
