# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_dashboard_service',
            fields=[
                ('csrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Service', models.CharField(default='Service', max_length=10, verbose_name='Service')),
                ('ctyp_desc', models.CharField(max_length=60, verbose_name='description')),
                ('csrv_due_date', models.DateField(verbose_name='duedate')),
                ('csac_service_date', models.DateField(verbose_name='servicedate')),
                ('csac_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='price')),
                ('average_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='average_price')),
                ('csac_price_last', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='lastprice')),
                ('csac_service_date_last', models.DateField(verbose_name='lastservicedate')),
                ('off_from_avg', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, verbose_name='off_from_avg')),
            ],
            options={
                'verbose_name_plural': 's_dashboard_service',
                'db_table': 's_dashboard_service',
                'managed': False,
                'verbose_name': 's_dashboard_service',
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceType',
            fields=[
                ('uprt_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Code')),
                ('uprt_desc', models.CharField(max_length=60, verbose_name='Description')),
                ('uprt_default_value', models.CharField(blank=True, max_length=40, null=True, verbose_name='Default value')),
                ('uprt_usage', models.TextField(blank=True, null=True, verbose_name='Usage')),
            ],
            options={
                'verbose_name_plural': 'UserPreferenceTypes',
                'db_table': 'oh_user_preference_types',
                'verbose_name': 'UserPreferenceType',
            },
        ),
    ]
