# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_userpreferencetype_v_dashboard_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='v_dashboard_service',
            options={'managed': False, 'verbose_name': 'v_dashboard_service', 'verbose_name_plural': 'v_dashboard_service'},
        ),
        migrations.AlterModelTable(
            name='v_dashboard_service',
            table='v_dashboard_service',
        ),
    ]
